import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List - Full Stack App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrollbar-hide`}>
        <div className="w-screen px-2 sm:px-5 md:px-20 lg:px-60 flex justify-center items-center flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
